server:
  port: 8080
spring:
  application:
    name: Inteagle            
  datasource:
     url: jdbc:mysql://localhost:3306/inteagle?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
     username: root
     password: root
     driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: inteagle2019
    port: 6379
    jedis:
     pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1 
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
mybatis:
  mapper-locations: classpath:mapper/*/*.xml     #mapper文件路径
  type-aliases-package: com.inteagle.*.entity  #实体类的包路径
#  configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置日志
logging:
  #配置日志文件路径
  path:  F:\logs\Inteagle
  config: classpath:logback.xml 
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error

mqtt:
  host: tcp://120.24.102.197:1883
  username: admin
  password: public
  topic: 6lbr-server/#
  #服务质量
  #0代表“至多一次”，消息发布完全依赖底层 TCP/IP 网络。会发生消息丢失或重复。这一级别可用于如下情况，环境传感器数据，丢失一次读记录无所谓，因为不久后还会有第二次发送。
  #1代表“至少一次”，确保消息到达，但消息重复可能会发生。
  #2代表“只有一次”，确保消息到达一次。这一级别可用于如下情况，在计费系统中，消息重复或丢失会导致不正确的结果。
  qos: 2
  #可配置多个mqtt服务器
  #服务器列表,多个以英文逗号拼接  
  hosts: tcp://120.24.102.197:1883
  #超时时间 单位为秒
  connectionTimeout: 10
  #会话心跳时间 单位为秒
  #若心跳时间过短，在消费端繁忙时会无法完成服务端的心跳回复导致服务端认为消费端下线而无法完成订阅
  #可采用MQ接收端和消费端之间加上队列
  keepAliveInterval: 10
  #消息发布者clientId
  publishClientId: my_publish_01
  #消息订阅者clientId
  subscribeClientId: my_subscribe_01



