server:
  port: 8080

spring:
  application:
    name: Inteagle            
  datasource:
     url: jdbc:mysql://localhost:3306/inteagle?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    password: inteagle2019
    port: 6379
    jedis:
     pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1 
      
mybatis:
  mapper-locations: classpath:mapper/*/*.xml     #mapper文件路径
  type-aliases-package: com.inteagle.*.*.entity  #实体类的包路径

#配置日志
logging:
  #配置日志文件路径
  path:  F:\logs\Inteagle
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error











